### ISSUE TITLE
Demo page is broken

### ISSUE THREAD

**Issue by PauloPaquielli** [codefoundries/UniversalRelayBoilerplate#286] opened 2017-01-25 19:10 UTC
![image](https://cloud.githubusercontent.com/assets/3427262/22305038/cf11b2f6-e318-11e6-9096-5a62fa5a6fe0.png)

**Comment by thelordoftheboards** [comment] 2017-01-26 09:14
Duplicate of #276

**Closed by thelordoftheboards** 2017-01-26 09:14 UTC
